### ISSUE TITLE
Fails to decode when the value is a base64 string

### ISSUE THREAD

**Issue by maraisr** [lukeed/qss#11]
When a base64 needs padding (`==`) at the _end??_; qss seems to not decode properly.

Take the following reproduction, compared against `query-string`:

```js
import {decode} from 'qss';
import {parse} from 'query-string';

const qs = 'abc=dGVzdA==&y=10'; // the y=10 here is just to see more than one value

console.log('qss', decode(qs));
console.log('query-string', parse(qs));

//~

/*
qss { abc: 'dGVzdA', y: 10 }
query-string [Object: null prototype] { abc: 'dGVzdA==', y: '10'
*/
```

> The `"dGVzdA=="` is a base64 string of the word _"test"_. JavaScript itself seems to be _loose_ in that this still decodes just fine, but passing this string into _strict_ systems like Auth0 or C# the decode of that base64 fails.

So as an aside question, if this lib was to remain js focused should we solve the use-case on the backend systems, and padd out the base64—or should `qss` decode with the equals?

**Comment by lukeed** [comment]
Hey, thanks

You're right that it probably should match. I haven't looked at the code for a while, but IIRC it's a pretty naiive `split()` approach. 

If you're doing this in the browser, this can be replaced via `new URLSearchParams('abc=dGVzdA==&y=10')` – if your [support range allows it](https://caniuse.com/urlsearchparams).
