### ISSUE TITLE
resolve empty query string values to undefined

### ISSUE THREAD

**Issue by Hotell** [lukeed/qss#3]
Hey Luke. First of thanks for this project. While using it I noticed one "strange" behaviour while decoding query string  from URL.

**Example:**

```js
const queryString = 'foo=foo&bar=bar1&moo='
const parsed = decode(queryString)

expect(parsed).toEqual({foo:'foo', bar: 'bar1', moo: 0 })
```

```js
const queryString = 'foo=foo&bar=bar1&moo'
const parsed = decode(queryString)

expect(parsed).toEqual({foo:'foo', bar: 'bar1', moo: 'undefined' })
```

I would suggest that empty query values `moo=` should not be casted to `number`/zero rather they should be set to `undefined` or empty string `''`.  `moo` example returns `'undefined'` as a string not value (that should be IMHO fixed as well, to be consistent).

WDYT?

I can send PR if you ok with my suggestion/report 👍

cheers

**Comment by lukeed** [comment]
Hey, thanks for this! Totally missed that & it's definitely an issue 

If you have a fix handy, by all means go for it. Otherwise I can bust out a fix this morning

**Comment by lukeed** [comment]
Hey, I had a spare moment this morning & was already doing something for `clsx` anyway.

Thank you for the report! Much appreciated 🙇
