### ISSUE TITLE
Browsers support?

### ISSUE THREAD

**Issue by VictorCazanave** [lukeed/qss#5]
Hello,
I'm thinking of using this library in my current project but there is no information about the browsers support.
Do you know which browsers are supported?

**Comment by lukeed** [comment]
Hey, I do :)

The `Array.isArray` usage is the "limiting factor" so [its support table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Browser_compatibility) is the answer. As you can see, it's quite old and so it's well supported -- IE9+

Hope that helps!

**Comment by VictorCazanave** [comment]
Great! Thanks for your quick answer @lukeed 😃 

Maybe it could be added in the documentation?
I think other people may be interested
